name-template: 'Version $NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
  - title: '👍 Enhancements'
    labels:
      - 'enhancement'   
      - 'documentation'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '⏩ Performance'
    labels:
      - 'performance'   
  - title: '🔧 Maintenance'
    labels: 
       - 'refactor'
       - 'test'
       - 'tests'
       - 'build'
  - title: '↜ Dependencies'
    labels:
      - 'dependencies'
      - 'dependency'
exclude-labels:
  - 'skip-changelog'  
  - 'release'
version-resolver:
  major:
    labels:
      - 'Major version'
  minor:
    labels:
      - 'Minor version'
  patch:
    labels:
      - 'Patch version'
  default: patch
change-template: '- [#$NUMBER]($URL): $TITLE (@$AUTHOR)'
template: |
  $CHANGES
