version: 1.0.0.{build}
image: Visual Studio 2019
configuration: Release
platform: Any CPU
build_script:
- ps: msbuild /t:restore,pack /p:Configuration=Release /p:IncludeSymbols=true /p:SymbolPackageFormat=snupkg /p:ContinuousIntegrationBuild=true /p:EmbedUntrackedSources=true /verbosity:minimal
test_script:
- ps: dotnet test tests\NLog.Targets.AppCenter.Tests\NLog.Targets.AppCenter.Tests.csproj
artifacts:
  - path: '**\NLog.*.nupkg'
  - path: '**\NLog.*.snupkg'
deploy:
- provider: NuGet
  api_key:
    secure: 0N4WVSWJBQkqD7O+hELLaxaxPSlsbWbHbk2t4MrxtYBRNfFd+uPViv7vla0ImG5b
  on:
    branch: master
