version: 1.0.0.{build}
image: Visual Studio 2022
configuration: Release
platform: Any CPU
build_script:
- ps: dotnet workload install maui macos android ios maccatalyst
- ps: msbuild /t:restore,pack /p:Configuration=Release /p:IncludeSymbols=true /p:SymbolPackageFormat=snupkg /p:ContinuousIntegrationBuild=true /p:EmbedUntrackedSources=true /p:PublishRepositoryUrl=true /verbosity:minimal
test_script:
- ps: dotnet test tests\NLog.Targets.AppCenter.Tests\NLog.Targets.AppCenter.Tests.csproj
artifacts:
  - path: '**\NLog.*.nupkg'
  - path: '**\NLog.*.snupkg'
deploy:
- provider: NuGet
  api_key:
    secure: 5tuxbM+Ujp0ZtaDCGYET23qKr6bJWo/Vzxlf7uTbspaf8R1R7sIe1JqSDHZoK1gV
  on:
    branch: master
